DELETE  http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0Mjg3MTIyLCJ1c2VySWQiOjF9.Xb4SAQcOKkxEP8eEPl1iNxX4smkJgVqCvveCiYrjApg